#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════
# update-hyprlock-theme.sh
# Place at: ~/.config/hypr/scripts/update-hyprlock-theme.sh
# chmod +x
#
# Usage:
#   update-hyprlock-theme.sh samurai
#   update-hyprlock-theme.sh arabic
#
# Reads pywal colors and writes ~/.config/hypr/hyprlock-theme.conf
# with the right palette, font, and placeholder for the active theme.
#
# Call this from your wallpaper-toggle script after running pywal.
# ═══════════════════════════════════════════════════════════

THEME="${1:-arabic}"
COLORS_FILE="$HOME/.cache/wal/colors"
OUTPUT="$HOME/.config/hypr/hyprlock-theme.conf"
THEME_STATE="$HOME/.config/hypr/.current-theme"

# ── Read pywal colors ──
if [[ ! -f "$COLORS_FILE" ]]; then
    echo "No pywal colors found at $COLORS_FILE"
    exit 1
fi

mapfile -t C < "$COLORS_FILE"

# ── Theme-specific settings ──
case "$THEME" in
    samurai)
        FONT="Noto Sans CJK JP"
        PLACEHOLDER='<span foreground="##958c77">⋯</span>'
        ;;
    arabic)
        FONT="Noto Sans Arabic"
        PLACEHOLDER='<span foreground="##958c77">⋯</span>'
        ;;
    *)
        FONT="JetBrainsMono Nerd Font"
        PLACEHOLDER='<span foreground="##958c77">⋯</span>'
        ;;
esac

# ── Write theme config ──
cat > "$OUTPUT" <<EOF
# Auto-generated by update-hyprlock-theme.sh — $(date)
# Theme: $THEME

\$font = $FONT
\$placeholder = $PLACEHOLDER

# Colors from pywal
\$bg      = rgba(${C[0]#\#}cc)
\$fg      = rgba(${C[7]#\#}ee)
\$muted   = rgba(${C[8]#\#}cc)
\$shadow  = rgba(${C[0]#\#}80)
\$accent1 = rgba(${C[1]#\#}cc)
\$accent2 = rgba(${C[2]#\#}cc)
\$accent3 = rgba(${C[3]#\#}ff)
EOF

# ── Save current theme for the clock script ──
echo "$THEME" > "$THEME_STATE"

echo "Wrote hyprlock theme ($THEME) to $OUTPUT"
