-- Border colors for the current theme. Regenerated by ~/.local/bin/wallpaper-toggle
-- from the pywal palette, then applied with `hyprctl reload`. Do not edit by hand.
return {
    active_border   = { colors = { "rgba(6F5F40ee)", "rgba(8B764Edd)", "rgba(776644cc)", "rgba(958c77bb)" }, angle = 135 },
    inactive_border = { colors = { "rgba(958c7788)", "rgba(0E0D0D55)" }, angle = 135 },
}
